openapi: "3.0.2"
info:
  title: Prioritizer
  version: "1.0"
servers:
  - url: https://localhost:8080
paths:
  /tree:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tree'
        '404':
          description: NOT FOUND
        '500':
          description: SERVER ERROR
  /tree/{categoryId}:
    parameters:
      - name: categoryId
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tree'
        '404':
          description: NOT FOUND
        '500':
          description: SERVER ERROR
    delete:
      responses:
        '204':
          description: NO CONTENT
  /tree/{categoryId}/subcategories:
    parameters:
      - name: categoryId
        in: path
        required: true
        schema:
          type: string
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: NOT FOUND
        '500':
          description: SERVER ERROR
  /tree/{categoryId}/items:
    parameters:
      - name: categoryId
        in: path
        required: true
        schema:
          type: string
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
                - link
              properties:
                name:
                  type: string
                price:
                  type: number
                link:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: NOT FOUND
        '500':
          description: SERVER ERROR
    patch:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: NOT FOUND
        '500':
          description: SERVER ERROR
components:
  schemas:
    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Item:
      type: object
      required:
        - id
        - name
        - price
        - link
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
        link:
          type: string
    Tree:
      type: object
      required:
        - category
        - queue
        - children
      properties:
        category:
          $ref: '#/components/schemas/Category'
        queue:
          type: array
          items:
            $ref: '#/components/schemas/Item'
